services:
  - type: web
    name: rucloud-api
    runtime: python
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi --log-file -
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://rucloud-api.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://rucloud-api.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: rucloud-db
          property: connectionString

databases:
  - name: rucloud-db
    region: frankfurt
    plan: free
    databaseName: rucloud
    user: rucloud
