services:
  - type: web
    name: rucloud-api
    runtime: python
    sourceDir: backend
    buildCommand: bash build.sh
    startCommand: gunicorn config.wsgi:application --workers=4 --max-requests=1200 --timeout=30
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rucloud-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,localhost"
      - key: CORS_ALLOWED_ORIGINS
        value: https://rucloud.vercel.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://rucloud.vercel.app
      - key: GUNICORN_CMD_ARGS
        value: "--access-logfile - --error-logfile -"

databases:
  - name: rucloud-db
    databaseName: rucloud
    plan: free
