# Generated by Django 6.0.3 on 2026-06-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ccp_ref',
            field=models.CharField(blank=True, help_text='CCP transaction reference provided by customer', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ccp', 'CCP / Postal Payment'), ('bank_transfer', 'Bank Transfer'), ('cod', 'Cash on Delivery')], default='ccp', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
