# Generated by Django 6.0.3 on 2026-06-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_ccp_ref_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_receipt',
            field=models.ImageField(blank=True, help_text='Uploaded payment receipt/screenshot', null=True, upload_to='payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('baridimob', 'BaridiMob'), ('ccp', 'CCP Transfer'), ('bank_transfer', 'Bank Transfer')], default='ccp', max_length=20),
        ),
    ]
