# Generated by Django 6.0.3 on 2026-06-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_receipt_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('domicile', 'À domicile'), ('stop_desk', 'Stop desk')], default='domicile', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='wilaya_code',
            field=models.IntegerField(blank=True, help_text='Algerian wilaya code', null=True),
        ),
    ]
