services:
  - type: web
    name: rucloud-api
    runtime: python
    sourceDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi --workers=4 --max-requests=1200 --timeout=30
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rucloud-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,localhost"
      - key: CORS_ALLOWED_ORIGINS
        value: https://rucloud.vercel.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://rucloud.vercel.app
      - key: VITE_API_URL
        value: https://rucloud-api.onrender.com/api

databases:
  - name: rucloud-db
    databaseName: rucloud
    plan: free
