# Generated by Django 6.0.3 on 2026-06-07 18:04

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Category.objects.update_or_create(slug='accessories', defaults={'name': 'Accessories', 'order': 10})


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcolor'),
    ]

    operations = [
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
